version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: perfume_shop_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
